# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos/exynos7885.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_A10_OPEN) := \
	exynos/exynos7884B-a10_eur_open_00.dtbo \
	exynos/exynos7884B-a10_eur_open_01.dtbo \
	exynos/exynos7884B-a10_kor_open_00.dtbo \
	exynos/exynos7884B-a10_kor_open_03.dtbo \
	exynos/exynos7884B-a10_kor_open_05.dtbo \
	exynos/exynos7884B-a10_swa_open_00.dtbo

always         := $(dtb-y) $(dtbo-y)
clean-files    := *.dtb *.dtbo
